"""initial migration

Revision ID: 4929c3b19c44
Revises: c28589fe51d6
Create Date: 2026-04-21 15:38:59.774778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4929c3b19c44'
down_revision: Union[str, Sequence[str], None] = 'c28589fe51d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('description', sa.String(length=200), nullable=False, server_default=''),
    )
    op.alter_column('products', 'description', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
